-- Close schema-migration drift: 5 models, 2 enums, 15+ fields
-- Generated by `prisma migrate diff --from-migrations --to-schema`

-- CreateEnum
CREATE TYPE "Plan" AS ENUM ('FREE', 'PRO', 'ENTERPRISE');

-- CreateEnum
CREATE TYPE "MobileDocumentStatus" AS ENUM ('DRAFT', 'SENT', 'PAID', 'CANCELLED');

-- CreateEnum
CREATE TYPE "EnterpriseRequestStatus" AS ENUM ('PENDING', 'CONTACTED', 'APPROVED', 'REJECTED');

-- CreateEnum
CREATE TYPE "TransactionStatus" AS ENUM ('PENDING', 'COMPLETED', 'FAILED', 'REFUNDED');

-- CreateEnum
CREATE TYPE "TransactionProvider" AS ENUM ('LEMON_SQUEEZY', 'EDAHABIA');

-- AlterEnum
ALTER TYPE "DocumentType" ADD VALUE 'INTERVENTION';
ALTER TYPE "DocumentType" ADD VALUE 'ATTACHEMENT';

-- AlterEnum
BEGIN;
CREATE TYPE "SubscriptionStatus_new" AS ENUM ('FREE', 'TRIAL', 'STANDARD', 'PRO', 'MAX', 'ENTERPRISE', 'EXPIRED');
ALTER TABLE "public"."User" ALTER COLUMN "subscriptionStatus" DROP DEFAULT;
ALTER TABLE "User" ALTER COLUMN "subscriptionStatus" TYPE "SubscriptionStatus_new" USING ("subscriptionStatus"::text::"SubscriptionStatus_new");
ALTER TYPE "SubscriptionStatus" RENAME TO "SubscriptionStatus_old";
ALTER TYPE "SubscriptionStatus_new" RENAME TO "SubscriptionStatus";
DROP TYPE "public"."SubscriptionStatus_old";
ALTER TABLE "User" ALTER COLUMN "subscriptionStatus" SET DEFAULT 'TRIAL';
COMMIT;

-- AlterTable
ALTER TABLE "Client" DROP COLUMN "ice",
DROP COLUMN "matriculeFiscal",
DROP COLUMN "siret",
ADD COLUMN     "ai" TEXT;

-- AlterTable
ALTER TABLE "Document" ADD COLUMN     "companyId" TEXT,
ADD COLUMN     "dueDate" TIMESTAMP(3),
ADD COLUMN     "language" TEXT NOT NULL DEFAULT 'fr',
ADD COLUMN     "logoPosition" TEXT;

-- AlterTable
ALTER TABLE "User" ADD COLUMN     "docCountThisMonth" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "lastDocResetAt" TIMESTAMP(3),
ADD COLUMN     "lemonsqueezyCustomerId" TEXT,
ADD COLUMN     "lemonsqueezySubscriptionId" TEXT,
ADD COLUMN     "maxTeamMembers" INTEGER NOT NULL DEFAULT 1,
ADD COLUMN     "storageUsedBytes" BIGINT NOT NULL DEFAULT 0;

-- CreateTable
CREATE TABLE "Company" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "nif" TEXT,
    "rc" TEXT,
    "nis" TEXT,
    "ai" TEXT,
    "phone" TEXT,
    "address" TEXT,
    "logo" TEXT,
    "signature" TEXT,
    "capital" TEXT,
    "tvaRate" INTEGER NOT NULL DEFAULT 19,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Company_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "LineItem" (
    "id" TEXT NOT NULL,
    "documentId" TEXT NOT NULL,
    "label" TEXT NOT NULL,
    "quantity" DOUBLE PRECISION NOT NULL,
    "unit" TEXT NOT NULL DEFAULT 'u',
    "unitPrice" DOUBLE PRECISION NOT NULL,
    "tvaRate" INTEGER NOT NULL DEFAULT 19,
    "totalHT" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "LineItem_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "PartnerClick" (
    "id" TEXT NOT NULL,
    "partnerId" TEXT NOT NULL,
    "code" TEXT NOT NULL,
    "ipHash" TEXT,
    "userAgent" TEXT,
    "referrer" TEXT,
    "landingPath" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "PartnerClick_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "EnterpriseRequest" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "companyName" TEXT NOT NULL,
    "employees" TEXT NOT NULL,
    "needs" TEXT NOT NULL,
    "phone" TEXT,
    "status" "EnterpriseRequestStatus" NOT NULL DEFAULT 'PENDING',
    "handledById" TEXT,
    "handledAt" TIMESTAMP(3),
    "notes" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "EnterpriseRequest_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Transaction" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "amount" DOUBLE PRECISION NOT NULL,
    "currency" TEXT NOT NULL DEFAULT 'DZD',
    "status" "TransactionStatus" NOT NULL DEFAULT 'PENDING',
    "provider" "TransactionProvider" NOT NULL,
    "providerId" TEXT,
    "planId" TEXT NOT NULL,
    "periodStart" TIMESTAMP(3),
    "periodEnd" TIMESTAMP(3),
    "description" TEXT,
    "metadata" JSONB NOT NULL DEFAULT '{}',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Transaction_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "Company_userId_key" ON "Company"("userId");

-- CreateIndex
CREATE INDEX "Company_userId_idx" ON "Company"("userId");

-- CreateIndex
CREATE INDEX "Company_nif_idx" ON "Company"("nif");

-- CreateIndex
CREATE INDEX "LineItem_documentId_idx" ON "LineItem"("documentId");

-- CreateIndex
CREATE INDEX "PartnerClick_partnerId_idx" ON "PartnerClick"("partnerId");

-- CreateIndex
CREATE INDEX "PartnerClick_createdAt_idx" ON "PartnerClick"("createdAt");

-- CreateIndex
CREATE INDEX "PartnerClick_code_idx" ON "PartnerClick"("code");

-- CreateIndex
CREATE INDEX "EnterpriseRequest_userId_idx" ON "EnterpriseRequest"("userId");

-- CreateIndex
CREATE INDEX "EnterpriseRequest_status_idx" ON "EnterpriseRequest"("status");

-- CreateIndex
CREATE INDEX "EnterpriseRequest_createdAt_idx" ON "EnterpriseRequest"("createdAt");

-- CreateIndex
CREATE INDEX "Transaction_userId_idx" ON "Transaction"("userId");

-- CreateIndex
CREATE INDEX "Transaction_status_idx" ON "Transaction"("status");

-- CreateIndex
CREATE INDEX "Transaction_createdAt_idx" ON "Transaction"("createdAt");

-- CreateIndex
CREATE INDEX "Transaction_providerId_idx" ON "Transaction"("providerId");

-- CreateIndex
CREATE INDEX "Transaction_userId_status_createdAt_idx" ON "Transaction"("userId", "status", "createdAt");

-- CreateIndex
CREATE INDEX "Client_userId_name_idx" ON "Client"("userId", "name");

-- CreateIndex
CREATE INDEX "Client_userId_nif_idx" ON "Client"("userId", "nif");

-- CreateIndex
CREATE INDEX "Client_userId_rc_idx" ON "Client"("userId", "rc");

-- CreateIndex
CREATE INDEX "Document_companyId_idx" ON "Document"("companyId");

-- CreateIndex
CREATE INDEX "Document_userId_type_status_createdAt_idx" ON "Document"("userId", "type", "status", "createdAt");

-- CreateIndex
CREATE INDEX "Document_userId_mode_idx" ON "Document"("userId", "mode");

-- CreateIndex
CREATE INDEX "Document_userId_country_idx" ON "Document"("userId", "country");

-- CreateIndex
CREATE INDEX "Notification_userId_read_createdAt_idx" ON "Notification"("userId", "read", "createdAt");

-- AddForeignKey
ALTER TABLE "Company" ADD CONSTRAINT "Company_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "LineItem" ADD CONSTRAINT "LineItem_documentId_fkey" FOREIGN KEY ("documentId") REFERENCES "Document"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Document" ADD CONSTRAINT "Document_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "Company"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PartnerClick" ADD CONSTRAINT "PartnerClick_partnerId_fkey" FOREIGN KEY ("partnerId") REFERENCES "Partner"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "EnterpriseRequest" ADD CONSTRAINT "EnterpriseRequest_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "EnterpriseRequest" ADD CONSTRAINT "EnterpriseRequest_handledById_fkey" FOREIGN KEY ("handledById") REFERENCES "Admin"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Transaction" ADD CONSTRAINT "Transaction_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
